CREATE SCHEMA proyecto_final;

USE proyecto_final;

CREATE TABLE Clientes (

	ID_CLIENTE INT auto_increment NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	INDEX idx_apellido(APELLIDO),
    INDEX idx_cliente(ID_CLIENTE)
);

CREATE TABLE Motos (

	ID_MOTO INT auto_increment NOT NULL PRIMARY KEY,
    MARCA VARCHAR(30) NOT NULL,
    MODELO VARCHAR(30) NOT NULL,
    CILINDRADA NUMERIC(4,0) NOT NULL,
	INDEX idx_cilindrada(CILINDRADA)
);

CREATE TABLE Cascos (

	ID_CASCO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	MODELO VARCHAR(30) NOT NULL,
	TALLE VARCHAR(30) NOT NULL
);

CREATE TABLE Ciudades (

	ID_CIUDAD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CIUDAD VARCHAR(30) NOT NULL,
    PAIS VARCHAR(30) NOT NULL,
	INDEX idx_ciudad(CIUDAD)
);

CREATE TABLE Alquileres (

    	ID_ALQUILER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    	ID_CLIENTE INT NOT NULL,
    	ID_MOTO INT NOT NULL,
    	ID_CIUDAD INT NOT NULL,
    	ID_CASCO INT NOT NULL,
    	PRECIO NUMERIC(8,0) NOT NULL,
    	FOREIGN KEY(ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE),
    	FOREIGN KEY(ID_MOTO) REFERENCES Motos(ID_MOTO),
    	FOREIGN KEY(ID_CIUDAD) REFERENCES Ciudades(ID_CIUDAD),
    	FOREIGN KEY(ID_CASCO) REFERENCES Cascos(ID_CASCO),
    	INDEX idx_alquiler(ID_ALQUILER)
);
